### ISSUE TITLE
Administrative sections - search for sections doesn't work

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#68] opened 2017-10-05 18:34 UTC
The layer in the picture has some points in the region (department) "Sud" but when I search for the region "Sud" I don't find it in the results

![image](https://user-images.githubusercontent.com/16922193/31246171-7fc89af0-a9da-11e7-8b80-6b0a908556de.png)

**Comment by ppasq** [comment] 2017-10-11 09:15
Fixed with #80

**Comment by gmtoglia** [comment] 2017-10-12 18:07
Paolo, is this based on a spatial request? If I search the department "Artibonite", the above mentioned layer (http://haitidata.dev.ithacaweb.org/layers/geonode:damagesecolespardepartemen) should not be there, but I still find it.

![image](https://user-images.githubusercontent.com/16922193/31511714-98ec8d3a-af56-11e7-9950-5d8924a2e759.png)

**Comment by ppasq** [comment] 2017-10-12 19:47
@gmtoglia, the spatial search works for extent and retrieve all the layers that intersect the rectangle defined by that extent. In this case some schools intersect the extent of Artibonite.

**Comment by ppasq** [comment] 2017-10-16 19:07
@gmtoglia can I close this?

**Comment by gmtoglia** [comment] 2017-10-29 17:52
Paolo, before closing it, do you think is possible to do a spatial search that "contains" instead of "intersect"?

**Comment by ppasq** [comment] 2017-10-30 10:38
Well, it is possible but what is the expected behaviour? You'll probably get an empty result in most cases.

**Comment by ppasq** [comment] 2017-11-02 09:01
Since the topic of this issue changed please open a new one.

**Closed by ppasq** 2017-11-02 09:01 UTC
Labels: enhancement
